# Generated by Django 4.2.6 on 2023-11-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_uid', models.CharField(max_length=200)),
                ('user_channel', models.CharField(max_length=200)),
            ],
        ),
    ]
