# Generated by Django 4.2.6 on 2024-01-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='user_channel',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='roommember',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='roommember',
            old_name='user_uid',
            new_name='uid',
        ),
    ]
